// DTO for creating new video game - no ID (auto-generated by API)
export interface CreateVideoGame {
  title: string;
  genre: string | null;
  releaseDate: Date | null;
  publisher: string | null;
  rating: number | null;
  price: number | null;
  description: string | null;
}
