using System.ComponentModel.DataAnnotations;

namespace VideoGameCatalogue.Core.Entities;

/// <summary>
/// Domain entity representing a video game in the catalogue.
/// Contains validation rules to maintain data integrity at the entity level.
/// </summary>
public class VideoGame
{
    /// <summary>
    /// Unique identifier - auto-generated by database
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Game title - required field with max length constraint
    /// </summary>
    [Required(ErrorMessage = "Title is required")]
    [StringLength(200, ErrorMessage = "Title cannot exceed 200 characters")]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Game genre (e.g., Action, RPG, Sports)
    /// </summary>
    [StringLength(50)]
    public string? Genre { get; set; }

    /// <summary>
    /// Official release date - nullable as some games may not have confirmed dates
    /// </summary>
    public DateTime? ReleaseDate { get; set; }

    /// <summary>
    /// Publisher/Developer name
    /// </summary>
    [StringLength(100)]
    public string? Publisher { get; set; }

    /// <summary>
    /// Game rating on 0-10 scale - nullable as not all games are rated
    /// Using decimal for precision (e.g., 8.5)
    /// </summary>
    [Range(0, 10, ErrorMessage = "Rating must be between 0 and 10")]
    public decimal? Rating { get; set; }

    /// <summary>
    /// Price in USD - nullable for free-to-play games
    /// </summary>
    [Range(0, 9999.99, ErrorMessage = "Price must be a positive value")]
    public decimal? Price { get; set; }

    /// <summary>
    /// Game description or summary
    /// </summary>
    [StringLength(1000)]
    public string? Description { get; set; }

    /// <summary>
    /// Audit field - when record was created (set automatically in repository)
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Audit field - when record was last updated (set automatically on updates)
    /// </summary>
    public DateTime? UpdatedAt { get; set; }
}